import '../styles/globals.css'
import { MoralisProvider } from "react-moralis";
import Head from 'next/head'
import Navbar from '../components/Navbar'
import SpaceLayout from '../components/Space/SpaceLayout';
import store from '../redux/store';
import { Provider } from 'react-redux'


const APP_ID = process.env.NEXT_PUBLIC_APP_ID
const SERVER_URL = process.env.NEXT_PUBLIC_SERVER_URL

function MyApp({ Component, pageProps, router }) {
  const showHeader = router.pathname === '/space' ? false : true;

  if (router.pathname.startsWith('/space')){
    return (
      <MoralisProvider appId={APP_ID} serverUrl={SERVER_URL}>
        <Provider store={store}>
          <SpaceLayout Component={Component}  pageProps={pageProps}/>
        </Provider>
        
    </MoralisProvider>
  )
  }
  return (
    <MoralisProvider appId={APP_ID} serverUrl={SERVER_URL}>
      <Provider store={store}>
      <Head>
        <title>CreatorSpace</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {showHeader && <Navbar />}
      <div className=' bg-zinc-900 h-full min-h-screen'>
        <Component {...pageProps} />
      </div>
      </Provider>
    </MoralisProvider>
  );
}

export default MyApp
