import '../styles/globals.css'
import { MoralisProvider } from "react-moralis";
import { useRouter } from 'next/router';
import Head from 'next/head'
import Navbar from '../components/Navbar'

const APP_ID = process.env.NEXT_PUBLIC_APP_ID
const SERVER_URL = process.env.NEXT_PUBLIC_SERVER_URL

function MyApp({ Component, pageProps }) {
  const router = useRouter();
  const showHeader = router.pathname === '/space' ? false : true;
  return (
    <MoralisProvider appId={APP_ID} serverUrl={SERVER_URL}>
      <Head>
        <title>CreatorSpace</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {showHeader && <Navbar />}
      
      <Component {...pageProps} />
    </MoralisProvider>
  );
}

export default MyApp
